apiVersion: v1
kind: Pod
metadata:
  name: pod-root-secure
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true